data_path: "../../DATA/LHCO/"
jet_per_event: 2
image_size: 40
image_w: 40
image_h: 40
ID: 100
W: 100
k: 50
memory_intensive: False
retrain: 0
steps: 100
reproc_arg_string: "w 0.5 s 1 N"
MiniBatch: False
signal_fraction: 0
train_interval:
  - 2600
  - 2700
eval_interval: 
  - 2600
  - 6000