# Input data directory
data_path: "/srv/beegfs/scratch/users/o/oleksiyu/DATA/LHCO/"
initial_file: "events_anomalydetection_v2.h5"
clustered_jets_file: "clustered_jets.h5"
jet_images_file: "jet_images_v2.h5"
sorted_bkg_file: "v2JetImSort_bkg.h5"
sorted_sig_file: "v2JetImSort_sig.h5"
sorted_bkg_mass_file: "mjj_bkg_sort.npy" 
sorted_sig_mass_file: "mjj_sig_sort.npy"

# Output directories
plots_directory: "plots/"
save_path: "/home/users/o/oleksiyu/CS/v4/"