seed: 2
output_path: "plots/compare/"
plot_name: "old_to_new05_1_maxdev5"
contamination_style: "mean_std"
# parametetrs for cs_eval
CSEconf: "config/cs_eval/maxdev5.yaml"

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: 
  - "old05_1"
  - "char/v2/k50Trueret0con0W2600_2700_w0.5s1Nboot/binnedW100s200ei26006000boot/"
title: "$n=0.5,\\sigma=1$, method 1"
density: 1

