seed: 2
output_path: "plots2/"
plot_name: "compare_old_dostributions"

labeling: ">5sigma"   # "kmeans_der" #"kmeans_der"#">5sigma"#
filterr: "med"
test_statistic: "chisq_ndof"
xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: 
  - "old00"
  - "old05_1"
title: "$n=0.5,\\sigma=1$, method 1"
density: 1

