seed: 2
output_path: "plots/"
plot_name: "prep05_1_maxdev5_MSD_CURTAINS_0005"
title: "$n=0.5,\\sigma=1$, maxdev5_MSD_CURTAINS_0005"
contamination_style: "Uall"
evaluate_the_worst_cases: False
do_plotting_in_contamination_evaluation: False
# parametetrs for cs_eval
CSEconf: ["config/cs_eval/maxdev5.yaml", "config/cs_eval/test_stat/max-sumnorm-dev.yaml"]

xlabel: "$\\tilde{\\chi}^2/n_{dof}$"

counts_windows_boot_load: "char/v2/k50MB100_3iret0con0W2600_2700_w0.5s1Nboot/binnedW100s16ei30004600boot/"

density: 1
#Different contaminatations (vertical lines on the plot)
contaminations:
  - 0.005
old_CS:
  - 0
cont_paths:
  - "char/v2/k50MB100_3iret0con0.05W2600_2700_w0.5s1Nrest/binnedW100s16ei30004600/"
colors:
  - "orange"
postfix:
  - "MB"
