
#overal run options
verbous: False 
plotting: False
save: False
save_path: "cs_performance_evaluation/"

# specify test statistic to compute:
labeling: "maxdev3"   
filterr: "med"
steal_sd_anomalypoor: 2

#random seed
sid: 0

test_statistic: "max-sumnorm-dev"
background_estim: "4_param_fit"